version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tfbase-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: minha_base
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    restart: unless-stopped
